In [561]:
import pandas as pd


In [562]:
data=pd.read_csv('movies.csv')

In [565]:
data.head(10)

Film      Genre            Lead Studio  \
0          Zack and Miri Make a Porno    romance  The Weinstein Company   
1                     Youth in Revolt     comedy  The Weinstein Company   
2  You Will Meet a Tall Dark Stranger     comedy            Independent   
3                        When in Rome     comedy                 Disney   
4               What Happens in Vegas     comedy                    Fox   
5                 Water For Elephants      drama       20th Century Fox   
6                              WALL-E  animation                 Disney   
7                            Waitress    romance            Independent   
8                 Waiting For Forever    romance            Independent   
9                     Valentine's Day     comedy           Warner Bros.   

   Audience score %  Profitability  Rotten Tomatoes % Worldwide Gross  Year  
0                70       1.747542                 64         $41.94   2008  
1                52       1.090000                 68         $19.62   2010  
2                35       1.211818                 43         $26.66   2010  
3                44       0.000000                 15         $43.04   2010  
4                72       6.267647                 28        $219.37   2008  
5                72       3.081421                 60        $117.09   2011  
6                89       2.896019                 96        $521.28   2008  
7                67      11.089741                 89         $22.18   2007  
8                53       0.005000                  6          $0.03   2011  
9                54       4.184038                 17        $217.57   2010

In [564]:
data['Genre']=data['Genre'].str.lower()
for i in range(77):
    if data['Genre'][i]=='comdy':
        data['Genre'][i]='comedy'
    if data['Genre'][i]=='romence':
        data['Genre'][i]='romance'
data=data.drop_duplicates()

In [225]:
type(data['Film'][0])


str

In [226]:
type(data['Genre'][0])

str

In [227]:
type(data['Lead Studio'][0])

str

In [229]:
type(data['Audience score %'][0])

numpy.int64

In [230]:
type(data['Profitability'][0])

numpy.float64

In [231]:
type(data['Rotten Tomatoes %'][0])

numpy.int64

In [232]:
type(data['Worldwide Gross'][0])

numpy.float64

In [233]:
type(data['Year'][0])

numpy.int64

In [566]:
data.dtypes

Film                  object
Genre                 object
Lead Studio           object
Audience score %       int64
Profitability        float64
Rotten Tomatoes %      int64
Worldwide Gross       object
Year                   int64
dtype: object

In [567]:
len(data[data['Genre']=='animation'])

3

In [568]:
data[(data['Genre']=='comedy') & (data['Year']==2007)]

Film   Genre   Lead Studio  Audience score %  Profitability  \
18  The Heartbreak Kid  comedy     Paramount                41       2.129444   
36     No Reservations  comedy  Warner Bros.                64       3.307180   
51      License to Wed  comedy  Warner Bros.                55       1.980206   
54          Knocked Up  comedy     Universal                83       6.636402   
62     Good Luck Chuck  comedy     Lionsgate                61       2.367685   
69           Enchanted  comedy        Disney                80       4.005737   

    Rotten Tomatoes % Worldwide Gross  Year  
18                 30        $127.77   2007  
36                 39         $92.60   2007  
51                  8         $69.31   2007  
54                 91           $219   2007  
62                  3         $59.19   2007  
69                 93        $340.49   2007

In [569]:
len(data[(data['Genre']=='animation') & (data['Audience score %']> 70)])

2

In [570]:
data.sort_values('Profitability', ascending=False).head()

Film    Genre  Lead Studio  \
68                           Fireproof    drama  Independent   
60  High School Musical 3: Senior Year   comedy       Disney   
14         The Twilight Saga: New Moon    drama       Summit   
7                             Waitress  romance  Independent   
12                            Twilight  romance       Summit   

    Audience score %  Profitability  Rotten Tomatoes % Worldwide Gross  Year  
68                51      66.934000                 40         $33.47   2008  
60                76      22.913136                 65        $252.04   2008  
14                78      14.196400                 27        $709.82   2009  
7                 67      11.089741                 89         $22.18   2007  
12                82      10.180027                 49        $376.66   2008

In [571]:
data[data['Genre']=='comedy'].sort_values('Audience score %', ascending=False).head()

Film   Genre   Lead Studio  Audience score %  \
54            Knocked Up  comedy     Universal                83   
76  (500) Days of Summer  comedy           Fox                81   
27      Sex and the City  comedy  Warner Bros.                81   
71             Beginners  comedy   Independent                80   
69             Enchanted  comedy        Disney                80   

    Profitability  Rotten Tomatoes % Worldwide Gross  Year  
54       6.636402                 91           $219   2007  
76       8.096000                 87         $60.72   2009  
27       7.221796                 49        $415.25   2008  
71       4.471875                 84         $14.31   2011  
69       4.005737                 93        $340.49   2007

In [572]:
data[(data['Lead Studio']=='Disney') & (data['Audience score %']> 70)]['Genre']

6     animation
16       comedy
22    animation
60       comedy
69       comedy
Name: Genre, dtype: object

In [573]:
data['Worldwide Gross'] = data['Worldwide Gross'].replace('[\$,]', '', regex=True).astype(float)

In [574]:
data[(data['Worldwide Gross']> 350) & (data['Audience score %']> 70)]

Film      Genre   Lead Studio  Audience score %  \
6                        WALL-E  animation        Disney                89   
12                     Twilight    romance        Summit                82   
14  The Twilight Saga: New Moon      drama        Summit                78   
22                      Tangled  animation        Disney                88   
27             Sex and the City     comedy  Warner Bros.                81   
45                   Mamma Mia!     comedy     Universal                76   

    Profitability  Rotten Tomatoes %  Worldwide Gross  Year  
6        2.896019                 96           521.28  2008  
12      10.180027                 49           376.66  2008  
14      14.196400                 27           709.82  2009  
22       1.365692                 89           355.01  2010  
27       7.221796                 49           415.25  2008  
45       9.234454                 53           609.47  2008

In [575]:
data[(data['Lead Studio']== 'Disney') & (data['Worldwide Gross']> 350) & (data['Audience score %']> 70)]

Film      Genre Lead Studio  Audience score %  Profitability  \
6    WALL-E  animation      Disney                89       2.896019   
22  Tangled  animation      Disney                88       1.365692   

    Rotten Tomatoes %  Worldwide Gross  Year  
6                  96           521.28  2008  
22                 89           355.01  2010

In [597]:
byGen=data.groupby('Genre')
byGen.mean().sort_values('Audience score %', ascending=False).drop(columns = ['Year'])

Audience score %  Profitability  Rotten Tomatoes %  Worldwide Gross
Genre                                                                         
fantasy           81.000000       1.783944          73.000000       285.430000
animation         76.333333       3.216561          80.333333       356.753333
drama             67.230769       8.407218          51.538462        99.011538
romance           65.600000       4.079972          46.266667       133.542000
comedy            61.095238       3.722986          42.809524       134.260476
action            45.000000       1.245333          11.000000        93.400000

In [579]:
data.sort_values('Rotten Tomatoes %', ascending=False).head()['Film']

6                WALL-E
69            Enchanted
43    Midnight in Paris
54           Knocked Up
73        A Serious Man
Name: Film, dtype: object

In [580]:
data[(data['Lead Studio']== 'Disney') & (data['Year']>2008)].sort_values('Worldwide Gross', ascending=False).head(3)
#The set asked for in the exercise is empty

Film      Genre Lead Studio  Audience score %  Profitability  \
22            Tangled  animation      Disney                88       1.365692   
16       The Proposal     comedy      Disney                74       7.867500   
64  Gnomeo and Juliet  animation      Disney                52       5.387972   

    Rotten Tomatoes %  Worldwide Gross  Year  
22                 89           355.01  2010  
16                 43           314.70  2009  
64                 56           193.97  2011

In [581]:
data['Lead Studio'].nunique()

13

In [582]:
data[(data['Lead Studio']== 'Disney') & (data['Year']>2008)].sort_values('Profitability', ascending=False).head(3)

Film      Genre Lead Studio  Audience score %  Profitability  \
16       The Proposal     comedy      Disney                74       7.867500   
64  Gnomeo and Juliet  animation      Disney                52       5.387972   
22            Tangled  animation      Disney                88       1.365692   

    Rotten Tomatoes %  Worldwide Gross  Year  
16                 43           314.70  2009  
64                 56           193.97  2011  
22                 89           355.01  2010

In [583]:
data.groupby('Lead Studio').count().sort_values('Film', ascending=False).head(1)



Film  Genre  Audience score %  Profitability  Rotten Tomatoes %  \
Lead Studio                                                                    
Independent    19     19                19             19                 19   

             Worldwide Gross  Year  
Lead Studio                         
Independent               19    19

In [263]:
data.groupby('Lead Studio').count().sort_values('Film', ascending=True).head(1)

Film  Genre  Audience score %  Profitability  Rotten Tomatoes %  \
Lead Studio                                                                    
CBS             1      1                 1              1                  1   

             Worldwide Gross  Year  
Lead Studio                         
CBS                        1     1

In [584]:
data.groupby('Lead Studio').mean().sort_values('Profitability', ascending=True).head(1)

Audience score %  Profitability  Rotten Tomatoes %  \
Lead Studio                                                                 
The Weinstein Company         68.666667       1.221114          71.666667   

                       Worldwide Gross         Year  
Lead Studio                                          
The Weinstein Company        23.273333  2009.666667

In [585]:
data.groupby('Lead Studio').mean().sort_values('Profitability', ascending=False).head(1)

Audience score %  Profitability  Rotten Tomatoes %  \
Lead Studio                                                       
Summit                   73.2       6.377962               39.2   

             Worldwide Gross    Year  
Lead Studio                           
Summit               248.452  2009.0

In [598]:
leadmean=data.groupby('Lead Studio').mean().drop(columns=['Year'])
leadmean[leadmean['Audience score %']>70]

Audience score %  Profitability  Rotten Tomatoes %  \
Lead Studio                                                       
Disney              71.857143       6.348008          65.285714   
Summit              73.200000       6.377962          39.200000   

             Worldwide Gross  
Lead Studio                   
Disney            288.647143  
Summit            248.452000

In [588]:
data[data['Rotten Tomatoes %']>50].groupby('Genre').count().sort_values('Film', ascending=False).tail(1)

Film  Lead Studio  Audience score %  Profitability  \
Genre                                                         
fantasy     1            1                 1              1   

         Rotten Tomatoes %  Worldwide Gross  Year  
Genre                                              
fantasy                  1                1     1

In [587]:
data[data['Genre']=='comedy'].groupby('Lead Studio').mean().rank()['Audience score %']['Fox']


12.0

In [589]:
data[data['Lead Studio']=='Independent'].groupby('Genre').count()['Film']

Genre
comedy     7
drama      4
romance    8
Name: Film, dtype: int64

In [2]:
import numpy as np

In [273]:
print(np.__version__)
np.show_config()

1.19.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [274]:
Z=np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [276]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


100

In [279]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [280]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [281]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [282]:
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [288]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [289]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [290]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [291]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.81798064 0.63235969 0.68450473]
  [0.2076382  0.09479328 0.59073053]
  [0.01935988 0.29486757 0.37738517]]

 [[0.75458631 0.43748853 0.6505689 ]
  [0.82880162 0.60631489 0.72095689]
  [0.18921601 0.51776394 0.96802344]]

 [[0.57872835 0.90155293 0.23889912]
  [0.93908727 0.30540003 0.17412724]
  [0.51000106 0.79668008 0.80697657]]]


In [292]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.01593624386246517 0.990234844184885


In [293]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.534619940374742


In [294]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [297]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [311]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 - 3 * 0.1)

nan
False
False
nan
True
-5.551115123125783e-17


In [3]:
Z = np.diag(1+np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [320]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [321]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [329]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [330]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.64256981  1.16862381 -0.97258543 -0.33231772  0.19263907]
 [ 1.26648073 -1.23263138 -0.61634804  1.15259882 -1.14699481]
 [-0.35127764 -0.00655652 -0.28117552  1.05982108  1.18650018]
 [-0.76534005 -0.23976701 -1.3444354   1.34543295  0.97022368]
 [-1.56195343 -0.15157317  1.40127253 -1.39324758  1.2951807 ]]


In [331]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

In [332]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [333]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [4]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5), -1))

9
10


In [355]:
Z=range(10)
Z<Z>Z

TypeError: '<' not supported between instances of 'range' and 'range'

In [360]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


In [361]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 7. 10. -2.  8. -3.  5. -7.  7. -9.  2.]


In [362]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[3 6 9]


In [363]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [364]:
_ = np.seterr(**defaults)

In [365]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [366]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [368]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2020-11-29 2020-11-30 2020-12-01


In [369]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [371]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(B,A,out=A)

array([-1.5, -1.5, -1.5])

In [372]:
Z = np.random.uniform(0,10,10)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[9. 8. 1. 5. 3. 7. 8. 9. 4. 2.]
[9. 8. 1. 5. 3. 7. 8. 9. 4. 2.]
[9. 8. 1. 5. 3. 7. 8. 9. 4. 2.]
[9 8 1 5 3 7 8 9 4 2]
[9. 8. 1. 5. 3. 7. 8. 9. 4. 2.]


In [373]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [374]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [375]:
np.info(np.fromiter)

fromiter(iterable, dtype, count=-1)

Create a new 1-dimensional array from an iterable object.

Parameters
----------
iterable : iterable object
    An iterable object providing data for the array.
dtype : data-type
    The data-type of the returned array.
count : int, optional
    The number of items to read from *iterable*.  The default is -1,
    which means all data is read.

Returns
-------
out : ndarray
    The output array.

Notes
-----
Specify `count` to improve performance.  It allows ``fromiter`` to
pre-allocate the output array, instead of resizing it on demand.

Examples
--------
>>> iterable = (x*x for x in range(5))
>>> np.fromiter(iterable, float)
array([  0.,   1.,   4.,   9.,  16.])


In [376]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [377]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.00555167 0.24657516 0.28063415 0.45368664 0.50568731 0.52104335
 0.53932686 0.74992622 0.77398594 0.85705282]


In [378]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [381]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


In [382]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [383]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.52523438 0.51220472 0.70466667 0.62344228 0.60934114 0.58154304
 0.91534507 0.90908043 0.71462364 0.79571262]
[1.29242586 0.67915208 0.80156928 0.18318203 1.22080737 0.89001047
 0.57192941 0.24817743 0.91921172 1.01290702]


In [384]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.35383203 0.01411102 0.83144938 0.         0.28103671 0.8869634
 0.80650189 0.30681311 0.09593828 0.63973693]


In [385]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [386]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [387]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [389]:
#np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [390]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

89


In [391]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [392]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.08162607 0.33128444 0.24734806 0.61068561 0.18568195
  0.53224446 0.24222744 0.29628654 0.40069483]
 [0.08162607 0.         0.38058922 0.16677157 0.66960456 0.10801255
  0.57738809 0.1658138  0.3501238  0.36514502]
 [0.33128444 0.38058922 0.         0.52406287 0.76493027 0.42739969
  0.74844352 0.45778111 0.04084395 0.73197183]
 [0.24734806 0.16677157 0.52406287 0.         0.7823146  0.09966365
  0.66709445 0.10360734 0.49913481 0.3125575 ]
 [0.61068561 0.66960456 0.76493027 0.7823146  0.         0.77323174
  0.15636425 0.83009758 0.72705615 0.63664369]
 [0.18568195 0.10801255 0.42739969 0.09966365 0.77323174 0.
  0.67366321 0.05789341 0.40446097 0.38706435]
 [0.53224446 0.57738809 0.74844352 0.66709445 0.15636425 0.67366321
  0.         0.72807751 0.70820541 0.48815354]
 [0.24222744 0.1658138  0.45778111 0.10360734 0.83009758 0.05789341
  0.72807751 0.         0.43873691 0.41373047]
 [0.29628654 0.3501238  0.04084395 0.49913481 0.72705615 0.40446097
  0.70820541 0.43873

In [394]:

from io import StringIO
# Fake file
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [395]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [396]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [397]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [399]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[6 5 0]
 [6 2 1]
 [6 9 6]]
[[6 2 1]
 [6 5 0]
 [6 9 6]]


In [400]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [401]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5090252296358855


In [402]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [403]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 4. 3. 2. 5. 4. 1. 5. 2. 2.]


In [404]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [410]:
data=[8, 12, 16, 24, 4]
ave=mean(data)
g=list(map(lambda x: abs(x-ave), data))
sum(g)

28.8

In [428]:
data=[8, 12, 16, 24, 4]
print(np.std(data))
data.extend([-24, 58])
print(np.std(data))

6.881860213634101
22.753335705216625


In [441]:
import scipy as sp
import scipy.stats as sps

In [594]:
I=np.random.exponential(1,100000)
print(sps.skew(I))

2.002526833669117


In [524]:
I=np.random.exponential(1,10000)
I=list(map(lambda x: round(x,3), I))
print(mean(I))
print(median(I))
print(sps.mode(I, axis=0, nan_policy='propagate')[0][0])
I[0]=14234
print(mean(I))
print(median(I))
print(sps.mode(I, axis=0, nan_policy='propagate')[0][0])

1.0109078
0.701
0.014
2.4339325000000005
0.701
0.014


In [527]:
I=[25,25,25,40,40,35,50,50,50,50]
np.std(I)

10.44030650891055

In [553]:
I=np.random.normal(size=1000000, loc=10, scale= 1.4)
np.quantile(I, 0.975)

12.741266065856319

In [554]:
#Debugging
def func1(a, b): 
    return a/b
def func2(x): 
    a=x
    b=x-1
    return func1(a, b)

In [557]:
%xmode Verbose
func2(1)

Exception reporting mode: Verbose


ZeroDivisionError: division by zero

In [559]:
%debug

> <ipython-input-554-7054065f2e66>(3)func1()
      1 #Debugging
      2 def func1(a, b):
----> 3     return a/b
      4 def func2(x):
      5     a=x

> <ipython-input-554-7054065f2e66>(7)func2()
      3     return a/b
      4 def func2(x):
      5     a=x
      6     b=x-1
----> 7     return func1(a, b)

> <ipython-input-557-180acea4108b>(2)<module>()
      1 get_ipython().run_line_magic('xmode', 'Verbose')
----> 2 func2(1)

*** Oldest frame
> <ipython-input-554-7054065f2e66>(7)func2()
      3     return a/b
      4 def func2(x):
      5     a=x
      6     b=x-1
----> 7     return func1(a, b)

> <ipython-input-554-7054065f2e66>(3)func1()
      1 #Debugging
      2 def func1(a, b):
----> 3     return a/b
      4 def func2(x):
      5     a=x

*** Newest frame
*** Newest frame
*** NameError: name 'x' is not defined
*** NameError: name 'x' is not defined
1
*** NameError: name 'qut' is not defined
